name = "telegroq"
main = "src/index.ts"
compatibility_flags = ["nodejs_compat", "nodejs_als"]
compatibility_date = "2024-04-29"
upload_source_maps = true
send_metrics = false

kv_namespaces = [
    { binding = "telegroq", id = "8e957c86318e4105b97471db2600ce74" },
]

[placement]
mode = "smart"

[ai]
binding = "ai"
